config/routes.rb
Blog::Application.routes.draw do

  resources :comments
  resources :posts

  resources :users, :only => [:update, :show] do
    collection do
      get 'edit'
    end
  end

  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :name
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :body, :title

  belongs_to :user
  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :name, :password, :password_confirmation

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authentication

  private
  def authentication
    # @authenticated = User.find(session[:user_id]) unless session[:user_id].nil?
    # Try to find a user
    @authenticated = User.where(:id => session[:user_id])

    #In the absense of a user, clear out the session
    if @authenticated.length == 0
      session[:user_id] = nil
      @authenticated = nil
    else
      # otherwise populate @authenticated with the user.
      @authenticated = @authenticated.first
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params[:comment])
    redirect_to @post
  end



  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # # GET /comments/new
  # # GET /comments/new.json
  # def new
  #   @comment = Comment.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @comment }
  #   end
  # end

  # # GET /comments/1/edit
  # def edit
  #   @comment = Comment.find(params[:id])
  # end

  # # POST /comments
  # # POST /comments.json
  # def create
  #   @comment = Comment.new(params[:comment])

  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
  #       format.json { render json: @comment, status: :created, location: @comment }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    @post.user = @authenticated

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.user_id != @authenticated.id
      redirect_to post_path(@post)
    end

    if @post.update_attributes(params[:post])
      redirect_to @post
    else
      render :edit
    end
  end


  def destroy
    @post = Post.find(params[:id])
    if @post.user_id != @authenticated.id
      redirect_to post_path(@post)
    else
      @post.destroy
    end
    redirect_to root_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name params[:name]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Incorrect login: Try Again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in


  def edit
    @user = @authenticated
    render :edit
  end


  def update
    @user = @authenticated
    if @user.update_attributes params[:user]
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def check_if_logged_in
    redirect_to(root_path) unless @authenticated.present?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def authentication_menu
    # Build a list of links depending on the user's permissions.
    links = ""
    if @authenticated.present?
      links += "<li>#{ link_to('New Post', new_post_path)}</li>"
      links += "<li>#{ link_to('Edit Account', edit_users_path(@authenticated))}</li>"
      links += "<li>#{ link_to('Logout ' + @authenticated.name, login_path, :method => 'delete') }</li>"
    else
      links += "<li>#{ link_to('Login', login_path) }</li>"
    end

    links
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
   <div class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header pull-right">
          <ul class="nav navbar-nav">
            <%== authentication_menu %>
          </ul>
        </div>
      </div>
    </div>

    <h1><%= link_to 'Blog', root_path %></h1>
  </header>

  <div class="container">
    <% if flash[:notice].present? %>
      <p>
      <%= flash[:notice] %>
      </p>
    <% end %>


    <%= yield %>
  </div> <!-- .container -->

</body>
</html>

app/views/pages/home.html.erb
<h2>Blog Home Page</h2>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, :autofocus => true %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing post</h2>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.reverse.each do |post| %>
  <section>
    <div class='post'>

      <h2><%= link_to post.title, post %></h2>
      <article>
        <p><%== post.body.gsub("\n", "<br>") %></p>
      </article>
      <footer>
        <p>By: Corinne <span><%= post.created_at.strftime("Posted: %B %d, %Y") %></span></p>
      </footer>

    </div>
  </section>
<% end %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <section>
    <div class='post'>
      <h2><%= @post.title %></h2>
      <article>
        <p><%== @post.body.gsub("\n", "<br>") %></p>
      </article>
      <footer>
        <p>By: Corinne <span><%= @post.created_at.strftime("Posted: %B %d, %Y") %></span></p>
      </footer>

      <%= link_to 'Back', posts_path, :class => 'post_buttons' %>

      <% if @authenticated.present? %>
          <%= link_to 'Edit', edit_post_path(@post), :class => 'post_buttons' %>
          <%= link_to 'Delete', post_path(@post), :class => 'post_buttons', :method => 'delete', :confirm => 'Are you sure you want to delete this post?' %>
      <% end %>

    </div>
  </section>

app/views/session/new.html.erb
<section>
  <div class="login">
    <h2>Login</h2>

    <%= form_tag '/login' do %>
      <%= label_tag 'name', nil, :autofocus => true %>
      <%= text_field_tag 'name' %>
      <%= label_tag 'password' %>
      <%= password_field_tag 'password' %>
      <%= submit_tag 'Login' %>
    <% end %>
  </div>
</section>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>


  <div class='field'>
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => 'Required' %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing user</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>New user</h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>